#!/bin/bash

bc -i <<< "$*"

#awk "BEGIN { print $* }; exit"
#python -c "print $*"
#perl -e "print $*"
#echo $* | bc
#bc <<< "$*"

#2.5e+2 scientific notation possible

#increment
#i=0; ((i++)) ; echo $i
