#!/usr/bin/python
import sys,argparse
parser = argparse.ArgumentParser(description="Take from input, one numerical value per line, and return the average of all",epilog='Author: Gildas Lepennetier')
parser.add_argument('-i', type=argparse.FileType('r'),default=sys.stdin, help='input file name, can take stdin')
parser.add_argument('-o', type=argparse.FileType('w'),default=sys.stdout, help='output file name, or stdout')


parser.add_argument('-e', type=argparse.FileType('w'),default=sys.stderr, help='error, log file, or stderr')
parser.add_argument('-c', type=str,default='mean_arithmetic', help='calculate using this function [mean_arithmetic]')
args=vars(parser.parse_args())

if args['c'] not in ['mean_arithmetic']:
	args['e'].write("ERROR function not recognized, or not available: %s\n"%(args['c']))

LIST=[]

def mean_arithmetic(n):
    return float(sum(n)) / max(len(n), 1)

i=0
for rline in args['i']:
	i+=1
	line=rline.split('\n')[0]
	try:
		LIST.append(float(line))
	except ValueError:
		args['e'].write("ERROR line %s: %s is not numerical\n"%(i,line))
if args['c'] == 'mean_arithmetic':
	args['o'].write("%s\n"%( mean_arithmetic(LIST) ))
