#!/bin/bash
my_needed_commands="$@"
missing_counter=0
for needed_command in $my_needed_commands; do
  if ! hash "$needed_command" >/dev/null 2>&1; then
    echo -e "Command not found in PATH: $needed_command\n" >&2
    ((missing_counter++))
  fi
done
if ((missing_counter > 0)); then
  echo -e "$missing_counter commands are missing in PATH, aborting\n" >&2
  exit 1
fi