#!/usr/bin/python
import sys, os
def usage():
	print("usage: %s [options] [-h help] [-d delimiter]"%( os.path.basename(sys.argv[0]) ) )
	print("")
	print("  Print names of column and column number.")
	print("\nOPTIONS:")
	print("  -         use a single minus to take input from stdin")
	print("  -o PATH   use this option(default stdout)")
	print("  -d DELIM  delimiter for input columns (default tab \\t)")
	print("  -s DELIM  delimiter for output columns (default tab \\t)")
	print("  -h        display help and exit")
	print("  -version  display version")
	print("  -author   display author information")
	print("")
	print("%s version 2.0"%os.path.basename(sys.argv[0]))
	print("Gildas Lepennetier - gildas.lepennetier@hotmail.fr")
	exit(0)
if len(sys.argv)==1:
	#no options=help & quit
	usage()
args=sys.argv[1:] #remove first argument = script name
if '-h' in args:
	usage()
if '-version' in args:
	print("%s version 2.0"%os.path.basename(sys.argv[0]))
	exit(0)
if '-author' in args:
	print("Gildas Lepennetier - gildas.lepennetier@hotmail.fr")
	exit(0)
sep_in="\t"
if '-d' in args:
	sep_in=args[ args.index('-d')+1 ]
	args.remove('-d') #remove option -d
	args.remove(sep_in) #remove option -d #remove delimiter after -d
sep_out="\t"
if '-s' in args:
	sep_out=args[ args.index('-s')+1 ]
	args.remove('-s') #remove option -d
	args.remove(sep_out) #remove option -d #remove delimiter after -d
	

if '-' in args:
	# here is from stdin
	index=0
	for name in sys.stdin.readline().split("\n")[0].split(sep_in):
		index+=1
		print("%s%s%s"%(index,sep_out,name))
	exit(0)
else:
	for filepath in args:
		if os.path.isfile(filepath):
			index=0
			with open (filepath) as fi:
				for name in fi.readline().split("\n")[0].split(sep_in):
					index+=1
					print("%s%s%s"%(index,sep_out,name))
		else:
			print("File not found at: %s"%filepath)
