#!/usr/bin/python3
import sys,re,os,argparse
parser = argparse.ArgumentParser(description="Expand a file using 'parent' grouping and 'order' ranking (intron number).\nex: .introns file with up and down informations about splice site, GC content etc....\n REQUIRED: a first line with name of columns",epilog='Author: Gildas Lepennetier: gildas.lepennetier@hotmail.fr')
parser.add_argument('-in', required=False, type=argparse.FileType('r'),default=sys.stdin, help='input file')
parser.add_argument('-out', required=False, type=argparse.FileType('w'),default=sys.stdout, help='output file')
parser.add_argument('-action',type=str,required=False,default='both',help='action to perform: up, down, or default: both')
parser.add_argument('-parent',type=int,required=True,help='column number for the parent. data will be concatenated using this. Be cafeful with duplicates')
parser.add_argument('-order',type=int,required=True,help='column number where the gathering number are')
parser.add_argument('-cols',type=str,required=True,help='column(s) to keep, separator for differents columns: ,')
parser.add_argument('-header', action='store_true',help='If you have an header')
parser.add_argument('-sep',type=str,default='\t',required=False,help='separator (default: \\t)')
parser.add_argument('-endline',type=str,default='\n',required=False,help='separator (default: unix \\n)')
parser.add_argument('--version', action='version', version='%(prog)s Final')
parser.add_argument('--verbose', '-v', action='count',default=0,help='add flag(s) to increase verbosity')# +1 for each -v flag
parser.add_argument('--copy',action='store_true',help='Display Copyright informations')
parser.add_argument('--author',action='store_true',help='Display author informations')
args=vars(parser.parse_args())
if args['author']:
    print ("LEPENNETIER Gildas - gildas.lepennetier@hotmail.fr")
    exit()
if args['copy']:
    print ("Copyright 2014 LEPENNETIER Gildas")
    exit()
VERB_LVL=args['verbose']
IN=args['in']
OUT=args['out']
sep=args['sep']
parent_index =args['parent']  -1
order_index=args['order']   -1
cols_list=args['cols']
action=args['action']
if action not in ['up','down','both']:
    sys.stderr.write("Error: -action should be up, down or both%s"%(args['endline']))
    parser.print_help()
    exit()
cols_list2=[]
cols_list=cols_list.split(',')
for i in cols_list: #transform the index of columns in python index-1
    i=int(i)
    cols_list2.append(i-1)
cols_list=cols_list2
del cols_list2
#logic of print the new line: old line + name with prefix "up_" or "down_"
#print ['up_%s'%(el) for el in [firstlineSplit[index] for index in cols_list]]
#print ['down_%s'%(el) for el in [firstlineSplit[index] for index in cols_list]]
Lines = IN.readlines()
if args['header']:# extract first line
    firstlineSplit=Lines[0].split(args['endline'])[0].split(sep)
    TO_write=[]
    if action in ['up','both']:
        TO_write+=['up_%s'%(el) for el in [firstlineSplit[index] for index in cols_list]]
    if action in ['down','both']:
        TO_write+=['down_%s'%(el) for el in [firstlineSplit[index] for index in cols_list]]
    OUT.write(sep.join(firstlineSplit+TO_write)   +args['endline'])
    Lines=Lines[1:]
DICO={}
for line in Lines:#### Gathering :  lines .split() BY parent
    line=line.split(args['endline'])[0]
    parent=line.split(sep)[parent_index]
    #OUT.write( line+'\n' )
    if parent not in DICO.keys():
        DICO[parent]=[line.split(sep)]
    elif parent in DICO.keys():
        DICO[parent].append(line.split(sep))
if VERB_LVL > 1:
    print(str(len(DICO.keys()))+' loading parents\n')
ALL_KEYS=DICO.keys()
ALL_KEYS.sort()
for CLE in ALL_KEYS:
    elementsNB=len(DICO[CLE])
    LISTES=DICO[CLE]
    nb_elems=len(LISTES)
    for line_REF in LISTES:
        current_nb=int(line_REF[order_index]) #current number in the 'order' (intron number in gene)
        line_UP  =[]   #reinitialization
        line_DOWN=[]
        for line_2 in LISTES:#fullfill the lines
            if int(line_2[order_index]) == current_nb -1:
                for index in cols_list:
                    line_UP.append(line_2[index])
            elif int(line_2[order_index]) == current_nb +1:
                for index in cols_list:
                    line_DOWN.append(line_2[index])
        if line_UP==[]:#UP fill the lines if index where first and last
            for el in cols_list:
                line_UP.append('')
        if line_DOWN==[]:#DOWN fill the lines if index where first and last
            for el in cols_list:
                line_DOWN.append('')
        TO_write=[]
        if action in ['up','both']:
            TO_write+=line_UP
        if action in ['down','both']:
            TO_write+=line_DOWN
        OUT.write(sep.join(line_REF  +  [el for el in TO_write]  ) +args['endline'])
