#!/bin/bash
function main () { if [ $# -lt 2 ];then echo "Usage: $(basename $0) <sep> <list of values space separated>"; else local IFS="$1"; shift; echo "$*"; fi; }
main $@ #a local default separator can only be init in a function
