#!/bin/bash
function main () { if [ $# -lt 2 ];then echo "Usage: join sep [list of values]"; else local IFS="$1"; shift; echo "$*"; fi; }
main $@ #a local default separator can only be init in a function