#!/usr/bin/env python



# Gildas Lepennetier script

import sys,argparse

if __name__ == "__main__":
	
	parser = argparse.ArgumentParser(description="Make clonal groups from changeo output (typically the *db-pass files).",epilog='Author: Gildas Lepennetier')

	parser.add_argument('-i',type=argparse.FileType('r'),default=sys.stdin,help='Input file (stdin)')
	parser.add_argument('-o',type=argparse.FileType('w'),default=sys.stdout,help='Output file (stdout)')
	parser.add_argument('-e',type=argparse.FileType('w'),default=sys.stderr,help='Error (stderr)')
	parser.add_argument('--version', action='version', version='%(prog)s 2017')#version display
	parser.add_argument('--copy',action='store_true',help='Display Copyright informations')
	parser.add_argument('--author',action='store_true',help='Display author informations')
	
	#8	V_CALL
	#9	D_CALL
	#10	J_CALL
	#37	CDR3
	
	parser.add_argument('-V', type=int,default=8,help='V-gene column')
	parser.add_argument('-D', type=int,default=9,help='D-gene column')
	parser.add_argument('-J', type=int,default=10,help='J-gene column')
	parser.add_argument('-CDR3', type=int,default=37,help='CDR3 column')
	
	args=vars(parser.parse_args())
		
	if args['author']:
		args['e'].write("LEPENNETIER Gildas - gildas.lepennetier@hotmail.fr\n")
		exit()
	if args['copy']:
		args['e'].write("Copyright 2017 LEPENNETIER Gildas\n")
		exit()
	
		
	DICO={}
	i=0
	for rline in args['i'].readlines():
		i+=1
		if i == 1: continue #skip first line
	
		line = rline.split("\r\n")[0].split("\n")[0].split("\t")
		ID_V=line[ args['V']-1].split(',')[0].split("-")[0]
		ID_D=line[ args['D']-1].split(',')[0].split("-")[0]
		ID_J=line[ args['J']-1].split(',')[0].split("*")[0]
		CDR3_LENGTH=len( line[ args['CDR3']-1] )
		ID = "%s\t%s\t%s\t%s"%(  ID_V, ID_D, ID_J, CDR3_LENGTH )
		
		if ID not in DICO:
			DICO[ID]=1
		else:
			DICO[ID]+=1
	print("nb_of_sequences\tV-gene\tD-gene\tJ-gene\tCDR3_length")
	for k in DICO:
		print( "%s\t%s"%(DICO[k], k))
		
	