#!/bin/bash
#first release 19 March 2014
############################ default values
CUR="$(pwd)"
VERSION="2.0 - 08.12.2015"
AUTHOR="Author: Gildas Lepennetier - gildas.lepennetier@hotmail.fr"
COPY="Copyright 2014-2015 LEPENNETIER Gildas"
SCRIPTSPATH="$HOME/MaxEnt_Humain/"
SPECIES="human"
SPECIESLIST="human drosophila"
SEP="\t"

header="no"	#default: no header: keep 

############################ define usage / help function
usage()
{
cat << EOF
USAGE: $(basename $0)
	-i path/to/file 
	-d donorColumn OR -a acceptorColumn
	[ options: -o outputName -s species -S path/to/scripts -t sep -H if header -V print version -A print author -h HELP ]

	Calculate the donor OR acceptor splice site strength based on Maximum Entropy model.
	
	The given file will be tested (Ns, length of sequence, GT- AG presence)
	The default output is <given file name>.MaxEnt
	Please provide information about header presence, or you may have an error.
	
INFORMATION
	The donor splice site should be:
		-3 +6 (GT)
		Ex:
		AAGGTAACA
	The acceptor splice site should be:
		-20 +3 (AG)
		Ex:
		CCCGAATTCGTCATCTGCAGCAG
		
ARGUMENTS
	OBLIGATORILY
	-i		Input file name
	-d		Donor splice site sequence index in the input file (first column = column 1)
	-a		Acceptor splice site sequence index in the input file
	OPTIONALS
	-H 		Header 		Flag to add if there is a header (first line with names) defaul: $header
	-o		Output 		(default: <infile>.MaxEnt)
	-s		Species		[ available:  $SPECIESLIST ] default: $SPECIES
	-S		Scripts		path to the perl scripts default: $SCRIPTSPATH
	-t		Separator	(default: tab >$SEP<)
	-V		Display version
	-A		Display author
	-h		Display help and exit
-----------------------
	This function wrap the usage of scripts created by:
	1) For Humans:
		Gene Yeo : geneyeo@mit.edu
		see also http://genes.mit.edu/burgelab/maxent/Xmaxentscan_scoreseq.html
	2) For Drosophila
		Joel McManus : mcmanus@andrew.cmu.edu
		(personnal communication)
-----------------------
	$AUTHOR
	$VERSION
	$COPY
EOF
}



############################ parse arguments
# put colon ":" after arguments that need a value in a variable. Ex: the flag -h don't need a value. same for V and A
if [ $# -lt 1 ];then
	echo "Error, please give arguments"
	echo "For help, type: $(basename $0) -h"
	exit 1
fi

while getopts "i:d:a:s:o:t:VAhH" OPTION; do
	case $OPTION in
		i) IN="$OPTARG";  ;;
		d) indexCol5ss="$OPTARG";;
		a) indexCol3ss="$OPTARG";;
		s) SPECIES="$OPTARG";;
		S) SCRIPTSPATH="$OPTARG";;
		o) OUT="$OPTARG";;
		H) header="yes";;
		t) SEP="$OPTARG";;
		V) echo $VERSION; exit 1;;
		A) echo $AUTHOR;  exit 1;;
		h) usage; exit 1;;
	esac
done

######## tests before run
# species in list of available species
if [[ ! $SPECIESLIST =~ $SPECIES ]];then echo "$SPECIES is not in available species list: $SPECIESLIST"; exit 1; fi

# check script folder
if [ ];then
fi
if [ ];then
fi
exit

# get from sources
#first: scripts are there
if [ ! -d $SCRIPTSPATH ];then
	echo "Error, scripts not found at: $MaxEntScript"
	echo -e "Downloading perl wrapers MaxEnt package:\nhttp://genes.mit.edu/burgelab/maxent/download/"
	wget -v "$MAXENTSCRIPTS" # MAXENTSCRIPTS="http://genes.mit.edu/burgelab/maxent/download/fordownload.tar.gz"
	tar -xf fordownload.tar.gz
	rm fordownload.tar.gz
	mv "fordownload" "$HOME/MaxEnt"
	MaxEntScript="$HOME/MaxEnt"
fi

echo "using scripts at $MaxEntScript"

# input file exist
if [ ! -e "$IN" ];then
	echo "Error, infile not found: '$IN'"
    exit 1
fi

# if oufile not set, make the default output name
if [ ! $OUT ];then
	OUT="$IN.MaxEnt"
fi

#check for index
if [ $indexCol5ss ];then
	if [ $indexCol3ss ];then
		echo "Error: please choose donor or acceptor scoring (give -a or -d with the index in file)"
		exit 1
	else
		TODO="donor"
	fi
else
	if [ $indexCol3ss ];then
		TODO="acceptor"
	else
		echo "Error: please choose donor or acceptor scoring (give -a or -d with the index in file)"
		exit 1
	fi
fi

#check for skip first line
#if [[ "$header" != "skip" && "$header" != "keep" ]];then echo "Error, please give skip/keep to -f (skip if you have a header, otherwise keep the first line)"; exit 1; fi

#check for Ns in the sequences
if [[ "$header" == "yes" ]];then
	if [ $indexCol5ss ];then #check n N in donor
		NB=$(cut -f $indexCol5ss $IN | tail -n +2 | grep -in N | wc -l)
		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
	fi
	if [ $indexCol3ss ];then #check n N in donor
		NB=$(cut -f $indexCol3ss $IN | tail -n +2 | grep -in N | wc -l)
		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
	fi
fi

if [[ "$header" == "no" ]];then
	if [ $indexCol5ss ];then #check n N in donor
		NB=$(cut -f $indexCol5ss $IN | grep -in N | wc -l)
		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
	fi
	if [ $indexCol3ss ];then #check n N in donor
		NB=$(cut -f $indexCol3ss $IN | grep -in N | wc -l)
		if [ $NB -gt 0 ]; then echo "error: there are some N on your sequences: $NB";exit; fi
	fi
fi





####################### MAIN #########################################
if [ $TODO == "donor" ];then
	#echo "donor"
	#extraction
	if [ $header == "yes" ]; then
		awk "BEGIN { FS=\"$SEP\"}{if(NR > 1) print \$$indexCol5ss }" $IN > "five"
	else
		awk "BEGIN { FS=\"$SEP\"}{print \$$indexCol5ss }" $IN > "five"
	fi
	#check length of sequence
	line=$(tail -n 1 "five" | cut -f $indexCol5ss)
	SIZE=${#line}
	if [ $SIZE -ne 9 ];then echo "Error: your donor sequence has a size != 9 ($SIZE)";rm "five"; exit 1; fi
	#check GT
	GT=${line:3:2}
	if [ $GT != "GT" ];then echo "Error: your donor sequence does not have the correct GT ($GT)"; exit 1; fi
	#check number of lines
	REF=$(wc -l <$IN)
	if [ $header == "yes" ]; then
		COUNT=$(( $(wc -l <"five") +1))
	else
		COUNT=$(( $(wc -l <"five") ))
	fi
	if [ $REF -ne $COUNT ];then
		echo "Error in MaxEnt: bad number of lines: five - $IN (check GT | skip first line) exit!"
		#rm "five"
		exit 1
	fi
	#move
	mv "five" "$MaxEntScript"
	cd "$MaxEntScript"
	#first line name
	if [ $header == "skip" ];then
		echo -e "seq5\tMaxEnt5" > "five.MaxEnt"
	fi
	#compute
	perl score5.pl "five" >> "five.MaxEnt"
	#clean
	rm "five"
	#move back
	mv "five.MaxEnt" $CUR
	cd $CUR
	#paste
	cut -f 2 "five.MaxEnt" > "five.MaxEnt2"
	paste "$IN" "five.MaxEnt2" > "$OUT"
	#clean
	rm "five.MaxEnt" "five.MaxEnt2"
	
else

if [ $TODO == "acceptor" ];then
	#echo "acceptor"
	#extraction
	if [ $header == "yes" ]; then
		awk "BEGIN { FS=\"$SEP\"}{if(NR > 1) print \$$indexCol3ss }" $IN > "three"
	else
		awk "BEGIN { FS=\"$SEP\"}{print \$$indexCol3ss }" $IN > "three"
	fi
	#check length of sequence
	line=$(tail -n 1 "three" | cut -f $indexCol3ss)
	SIZE=${#line}
	if [ $SIZE -ne 23 ];then echo "Error: your acceptor sequence has a size != 23 ($SIZE) exit! "; rm "three"; exit 1; fi
	#check AG
	AG=${line:18:2}
	if [ $AG != "AG" ];then echo "Error: your donor sequence does not have the correct AG ($AG) exit!"; exit 1; fi
	#check number of lines
	REF=$(wc -l <$IN)
	if [ $header == "yes" ]; then
		COUNT=$(( $(wc -l <"three") +1))
	else
		COUNT=$(( $(wc -l <"three") ))
	fi
	if [ $REF -ne $COUNT ];then
		echo "Error in MaxEnt: bad number of lines: three - $IN (check AG | skip first line) exit!"
		#rm "three"
		exit 1
	fi
	#move
	mv "three" "$MaxEntScript"
	cd "$MaxEntScript"
	#first line name
	if [ $header == "skip" ];then
		echo -e "seq3\tMaxEnt3"> "three.MaxEnt"
	fi
	#compute
	perl score3.pl "three" >> "three.MaxEnt"
	#clean
	rm "three"
	#move back
	mv "three.MaxEnt" $CUR
	cd $CUR
	#paste
	cut -f 2 "three.MaxEnt" > "three.MaxEnt2"
	paste "$IN" "three.MaxEnt2" > "$OUT"
	#clean
	rm "three.MaxEnt" "three.MaxEnt2"
fi
fi
