#!/usr/bin/env python

# Gildas Lepennetier script

import sys,argparse,re
import string #for the pattern replacement in string

def parse_range_and_list(string):
	"""Used to parse a string with comas and colons to define ranges."""
	LIST=[]
	if string:
		for elem1 in string.split(','):
			RANGES=elem1.split(':')
			if len(RANGES) == 1:
				LIST.append(int(RANGES[0]))
			if len(RANGES) == 2:
				for i in range( int(RANGES[0]), int(RANGES[1])+1 ):
					LIST.append( i )
			if len(RANGES) == 3:
				for i in range( int(RANGES[0]), int(RANGES[1])+1, int(RANGES[2]) ):
					LIST.append( i )
			if len(RANGES) > 3:
				sys.stderr.write("Error: bad range %s"%(RANGES))
				exit(1)
	return (LIST)

def mutations_positions( string, reference, add=0):
	if len(string) != len(reference):
		sys.tsderr.write("ERROR: not same sequence length\n")
	POSI=[]
	for index in range(0,len(string)):
		if string[index] in ['.','-','N','n']: #IGNORE points and minus
			continue
		if string[index] != reference[index]:
			POSI.append(index+add+1)#+1 because python indexes
			#the
	return (POSI)
	

if __name__ == "__main__":
	
	parser = argparse.ArgumentParser(description="Calculate the distance between Ig sequences, typically from the output of ParseDb.py from changeo.",epilog='Author: Gildas Lepennetier')

	parser.add_argument('-i',type=argparse.FileType('r'),default=sys.stdin,help='Input file (stdin)')
	parser.add_argument('-o',type=argparse.FileType('w'),default=sys.stdout,help='Output file (stdout)')
	parser.add_argument('-e',type=argparse.FileType('w'),default=sys.stderr,help='Error (stderr)')
	
	parser.add_argument('-ih',action='store_true',default=False,help='input header, add if you have a header in the intput')
	parser.add_argument('-oh',action='store_true',default=False,help='Output header, add if you want a header in the output')
	
	
	parser.add_argument('-FR1', type=int,default=31,help='FR1 column')
	parser.add_argument('-FR2', type=int,default=32,help='FR2 column')
	parser.add_argument('-FR3', type=int,default=33,help='FR3 column')
	parser.add_argument('-FR4', type=int,default=34,help='FR4 column')
	parser.add_argument('-CDR1', type=int,default=35,help='CDR1 column')
	parser.add_argument('-CDR2', type=int,default=36,help='CDR2 column')
	parser.add_argument('-CDR3', type=int,default=37,help='CDR3 column')
	parser.add_argument('-GL', type=int,default=46,help='Germline column')
	
	parser.add_argument('-FR1_maxGapNb', type=int,default=6,help='max number of . in the FR1 (6)')
	parser.add_argument('-FR2_maxGapNb', type=int,default=6,help='max number of . in the FR2 (6)')
	parser.add_argument('-FR3_maxGapNb', type=int,default=6,help='max number of . in the FR3 (6)')
	parser.add_argument('-FR4_maxGapNb', type=int,default=6,help='max number of . in the FR4 (6)')
	parser.add_argument('-CDR1_maxGapNb', type=int,default=12,help='max number of . in the CDR1 (12)')
	parser.add_argument('-CDR2_maxGapNb', type=int,default=12,help='max number of . in the CDR2 (12)')
	parser.add_argument('-CDR3_maxGapNb', type=int,default=12,help='max number of . in the CDR3 (12)')
	parser.add_argument('-GL_maxGapNb', type=int,default=24,help='max number of . in the Germline')
	
	parser.add_argument('-extracolumns', type=str,default='',help='Print extra column in addition. from:to a,b,... ')
	
	# indels will be ignored for now
	#parser.add_argument('-include_indels',action='store_true',default=False,help='Indel are - in the sequence. They are not hypermutations. Add this option to count them as mutations')
	parser.add_argument('-mutation_nb',action='store_true',default=False,help='Add number of mutations')
	parser.add_argument('-sizes',action='store_true',default=False,help='Add sizes for each region')

	parser.add_argument('--version', action='version', version='%(prog)s 2017')#version display
	parser.add_argument('--copy',action='store_true',help='Display Copyright informations')
	parser.add_argument('--author',action='store_true',help='Display author informations')
	args=vars(parser.parse_args())
		
	if args['author']:
		args['e'].write("LEPENNETIER Gildas - gildas.lepennetier@hotmail.fr\n")
		exit()
	if args['copy']:
		args['e'].write("Copyright 2017 LEPENNETIER Gildas\n")
		exit()
	
	#parse the extra columns
	COLS=[]
	if args['extracolumns']:
		COLS = parse_range_and_list(args['extracolumns'])

		
	linecounter=0
	for rline in args['i'].readlines():
		linecounter+=1
		
		line=rline.split('\r\n')[0].split('\n')[0].split('\t') #remove also windows eol, pRESTO output is like that
		
		if args['oh'] and linecounter == 1:
			FIRSTLINE=["FR1_MutationsPositions","CDR1_MutationsPositions","FR2_MutationsPositions","CDR2_MutationsPositions","FR3_MutationsPositions","CDR3_MutationsPositions","FR4_MutationsPositions"]
			EXTRA=[]
			if args['mutation_nb']:
				EXTRA=EXTRA+["FR1_mutation_nb","CDR1_mutation_nb","FR2_mutation_nb","CDR2_mutation_nb","FR3_mutation_nb","CDR3_mutation_nb","FR4_mutation_nb"]
			if args['sizes']:
				EXTRA=EXTRA+["FR1_size","CDR1_size","FR2_size","CDR2_size","FR3_size","CDR3_size","FR4_size"]
			if args['extracolumns']:
				EXTRA=EXTRA+[ line[i-1] for i in COLS ]
			args['o'].write("\t".join( FIRSTLINE + EXTRA) + "\n")
		
		if args['ih'] and linecounter == 1:
			continue
		
		FR1=line[ args['FR1']-1 ]
		FR2=line[ args['FR2']-1 ]
		FR3=line[ args['FR3']-1 ]
		FR4=line[ args['FR4']-1 ]
		CDR1=line[ args['CDR1']-1 ]
		CDR2=line[ args['CDR2']-1 ]
		CDR3=line[ args['CDR3']-1 ]
		GL=line[ args['GL']-1 ]
		
		if len(GL) != len(FR1)+len(FR2)+len(FR3)+len(FR4)+len(CDR1)+len(CDR2)+len(CDR3):
			args['e'].write("ERROR: length of Germline do not match the sum of the length of CDRs and FRs (line %s in file %s)\n"%(linecounter,args['i'].name ))
			continue
		ERRORS=[]
		if len( FR1.replace(".","")) == 0:
			ERRORS.append("FR1")
		if len( FR2.replace(".","")) == 0:
			ERRORS.append("FR2")
		if len( FR3.replace(".","")) == 0:
			ERRORS.append("FR3")
		if len( FR4.replace(".","")) == 0:
			ERRORS.append("FR4")
		if len( CDR1.replace(".","")) == 0:
			ERRORS.append("CDR1")
		if len( CDR2.replace(".","")) == 0:
			ERRORS.append("CDR2")
		if len( CDR3.replace(".","")) == 0:
			ERRORS.append("CDR3")
		if len( GL.replace(".","")) == 0:
			ERRORS.append("Germline")
		if len(ERRORS) > 0:
			args['e'].write("ERROR: %s regions made only with points (line %s in file %s, regions: %s)\n"%(len(ERRORS),linecounter,args['i'].name, ",".join(ERRORS) ))
			continue
		
		ERRORS=[]
		if FR1.count('.') > args['FR1_maxGapNb']:
			 ERRORS.append('FR1')
		if FR2.count('.') > args['FR2_maxGapNb']:
			 ERRORS.append('FR2')
		if FR3.count('.') > args['FR3_maxGapNb']:
			 ERRORS.append('FR3')
		if FR4.count('.') > args['FR4_maxGapNb']:
			 ERRORS.append('FR4')
		if CDR1.count('.') > args['CDR1_maxGapNb']:
			 ERRORS.append('CDR1')
		if CDR2.count('.') > args['CDR2_maxGapNb']:
			 ERRORS.append('CDR2')
		if CDR3.count('.') > args['CDR3_maxGapNb']:
			 ERRORS.append('CDR3')
		if GL.count('.') > args['GL_maxGapNb']:
			 ERRORS.append('Germline')
		if len(ERRORS) > 0:
			args['e'].write("ERROR: %s regions fail the _maxGapNb test (line %s in file %s, regions: %s)\n"%(len(ERRORS),linecounter,args['i'].name, ",".join(ERRORS) ))
			continue
		
		
		if GL.count('-') > 0:
			args['e'].write("ERROR: Germline contain indels -> programm has to be updated\n")
			exit(1)
			
		OUT=[]
		# gaps: just replace several --- by one to make it count as 1 mutation

		
		#option_gap : skip -, 2 - = 2 mutation, 2 - = 1 mutation
		
		FR1_mut_list = mutations_positions( FR1, GL[ 0:len(FR1) ], add=0)
		CDR1_mut_list= mutations_positions( CDR1, GL[ len(FR1) : (len(FR1)+len(CDR1)) ], add=len(FR1) )
		FR2_mut_list = mutations_positions( FR2, GL[ (len(FR1)+len(CDR1)) : (len(FR1)+len(CDR1)+len(FR2)) ], add=(len(FR1)+len(CDR1)))
		CDR2_mut_list= mutations_positions( CDR2, GL[ (len(FR1)+len(CDR1)+len(FR2)) : (len(FR1)+len(CDR1)+len(FR2)+len(CDR2)) ], add=(len(FR1)+len(CDR1)+len(FR2)) )
		FR3_mut_list = mutations_positions( FR3, GL[ (len(FR1)+len(CDR1)+len(FR2)+len(CDR2)) : (len(FR1)+len(CDR1)+len(FR2)+len(CDR2)+len(FR3)) ], add=(len(FR1)+len(CDR1)+len(FR2)+len(CDR2)) )
		CDR3_mut_list= mutations_positions( CDR3, GL[ (len(FR1)+len(CDR1)+len(FR2)+len(CDR2)+len(FR3)) : (len(FR1)+len(CDR1)+len(FR2)+len(CDR2)+len(FR3)+len(CDR3)) ] , add=(len(FR1)+len(CDR1)+len(FR2)+len(CDR2)+len(FR3)) )
		FR4_mut_list = mutations_positions( FR4, GL[ (len(FR1)+len(CDR1)+len(FR2)+len(CDR2)+len(FR3)+len(CDR3)) : (len(FR1)+len(CDR1)+len(FR2)+len(CDR2)+len(FR3)+len(CDR3)+len(FR4)) ], add=(len(FR1)+len(CDR1)+len(FR2)+len(CDR2)+len(FR3)+len(CDR3)) )
		
		OUT=[ ",".join( [ str(e) for e in FR1_mut_list]),
				 ",".join( [ str(e) for e in CDR1_mut_list]),
				 ",".join( [ str(e) for e in FR2_mut_list]),
				 ",".join( [ str(e) for e in CDR2_mut_list]),
				 ",".join( [ str(e) for e in FR3_mut_list]),
				 ",".join( [ str(e) for e in CDR3_mut_list]),
				 ",".join( [ str(e) for e in FR4_mut_list])]
		
		EXTRA=[]
		if args['mutation_nb']:
			EXTRA=EXTRA+[len(FR1_mut_list),len(CDR1_mut_list),len(FR2_mut_list),len(CDR2_mut_list),len(FR3_mut_list),len(CDR3_mut_list),len(FR4_mut_list)]
		if args['sizes']:
			EXTRA=EXTRA+[len(FR1),len(CDR1),len(FR2),len(CDR2),len(FR3),len(CDR3),len(FR4)]
		if args['extracolumns']:
			EXTRA=EXTRA+[ line[i-1] for i in COLS ]
		args['o'].write( "\t".join([ str(el) for el in OUT+EXTRA ]) +"\n")
		
