#!/bin/bash

re='^[0-9]+$'
if [ $# -ne 2 ]; then echo "Usage: $(basename $0) <integer> <file>" >&2; exit 1 ; fi
if ! [[ $1 =~ $re ]] ; then echo "Error: give a line number as integer" >&2; exit 1 ; fi
if ! [ -f "$2" ]; then echo "Error: not a regular file $2" >&2 ; exit 1 ; fi
sed "${1}q;d" $2
