#!/usr/bin/python
# -*- coding: utf-8 -*-
import argparse
import itertools
parser = argparse.ArgumentParser(description='Create sequences.',epilog='Author: Gildas Lepennetier: gildas.lepennetier@hotmail.fr')
parser.add_argument('-l','-length',help='Length of the sequence.')#todo: Can be coma separated in the form: from,to or from,to,by ??
parser.add_argument('-a','-alphabet',help='Alphabet to use.')
parser.add_argument('-i','-insensitive',action='store_true',help='Case insensitive, output will be in lower case.')
parser.add_argument('-u','-upper',action='store_true',help='Converted output to upper case.')
parser.add_argument('-V','--version', action='version', version='%(prog)s 29-04-2015')
parser.add_argument('-C','--copy',action='store_true',help='Display Copyright informations')
parser.add_argument('-A','--author',action='store_true',help='Display author informations')
args=vars(parser.parse_args())
if args['author']:
    print ("LEPENNETIER Gildas - gildas.lepennetier@hotmail.fr")
    exit()
if args['copy']:
    print ("Copyright 2015 LEPENNETIER Gildas")
    exit()
if not args['l']:
    print ("Error: length of sequence required")
    exit()
if not args['a']:
    print ("Error: alphabet required")
    exit()
L=int(args['l'])#split(',')
A=[a for a in args['a']] 
if args['i']:#case insensitive: everything lower
    A=[a.lower() for a in A]
if args['u']:#if output upper: everything upper
    A=[a.upper() for a in A]
A=list(set(A))#remove duplicates in alphabet
generator = itertools.product( ''.join(A), repeat=L)
for a in generator:
    print(''.join(a))
