#!/usr/bin/python
import sys,argparse
parser = argparse.ArgumentParser(description="Take from output, count and make table: count -- element counted",epilog='Author: Gildas Lepennetier')

parser.add_argument('-i', type=argparse.FileType('r'),default=sys.stdin, help='input file name, can take stdin')
parser.add_argument('-o', type=argparse.FileType('w'),default=sys.stdout, help='output file name, or stdout')

parser.add_argument('-s',action='store_true',help='Sort output')

args=vars(parser.parse_args())


DICO = {}
for rline in args['i']:
	line=rline.split('\n')[0]
	try:
		DICO[line]+=1
	except KeyError:
		DICO[line]=1
if args['s']:
	for k in sorted( DICO.keys() ):
		args['o'].write("%s\t%s\n"%(DICO[k],k))
else:
	for k in DICO.keys():
		args['o'].write("%s\t%s\n"%(DICO[k],k))