#!/bin/bash
echo -e "
#====================
# what to do next ?
#====================

	#==== projects
		+ D mel: gene expression
			+ remake the article figures using high and low expressed genes
		+ presence absence
			+ read papers

	#==== inproving functions

		+ multiprocess for match
		+ fix problem with duplicated ids

	#==== personal improvement

		+ multiprocess
		+ spider/crawler for articles
		+ website update splicing page -> big summary good for the final thesis
		+ ftp server to make avalable data
		+ github
"
echo -e "Modify this:\nnano $0\n"
