#!/bin/bash -e
if [ $2 ];then #default parameter: 80 char per line max
	len=$2
else len=80
fi
if [ -e "$1" ];then
	fold $1 -w $len -s
else
	echo -e "usage: $(basename $0) FILENAME MAXCHAR\n\n\tThis function take FILENAME in input, and use fold function to reshape the text in MAXCHAR per line (word wrap)"
	exit 1
fi
