#!/bin/bash
USAGE="\
Usage: $(basename $0) FUN DUR WAIT\
\n\
\n\tFUN:\tname of the function/script\
\n\tDUR:\tin seconde, for how long\
\n\tWAIT:\tin secondes, sleep between each repetition\
\n\
Author: Gildas Lepennetier"
if [ $# -eq 0 ];then echo -e $USAGE; exit; fi
FUN=$1
checkcmd "$FUN"
DUR=$2
WAIT=$3
ARGS="$4"
STEPS=$(( $2 / $3 ))
echo "run $FUN during $DUR s, wait $WAIT"
for e in $(seq 1 $STEPS);do
	echo "$e / $STEPS - $(date)"
	$1
	sleep $WAIT
done
